### ISSUE TITLE
LoginKey

### ISSUE THREAD

**Issue by Boryyy** [michikxd/hourbooster#3]
![image](https://user-images.githubusercontent.com/60760570/97239353-b072d080-17eb-11eb-825b-2c702bc7086f.png)

hey can u please update the bot so we can put the loginkey ? thanks.

**Comment by michikxd** [comment]
Hello, i dont want that because a lot of people are boosting their main accounts and they dont have a SDA. But if you have little bit of js knowledge you can do it. 

```
const logOnOptions = {
    accountName: config.username,
    password: config.password
    twoFactorCode: SteamTotp.generateAuthCode(config.sharedSecret)
};
```

And in config.json

```
{
    "username":"username here",
    "password":"password here",
    "sharedSecret":"sharedsecret here"
}
```
Also you need to install steam-totp moduls `npm install steam-totp` and require it via `const SteamTotp = require("steam-totp");`
this should help to you.

**Comment by Boryyy** [comment]
thanks alot <3

**Comment by Boryyy** [comment]
"     password: config.password, " u forgot " , " update it or i did it dw

**Comment by michikxd** [comment]
Oh sorry, edited. Btw you can star the repo i appreciate it!
